import {fresh,questions,compatible,yaml,markdown,upgrade} from './model.js';
const $=id=>document.getElementById(id),key='afs-dialogue-v0.1.0';let record=fresh(),storage=true;
try{const saved=JSON.parse(localStorage.getItem(key));if(compatible(saved))record=upgrade(saved);}catch{storage=false;}
function announce(text){$('message').textContent=text;}
function save(){try{localStorage.setItem(key,JSON.stringify(record));}catch{storage=false;}update();}
function update(){const resolved=record.decisions.filter(d=>d.status!=='open').length;$('progress').textContent=`${resolved} of ${questions.length} resolved`;$('meter').value=resolved;$('open-list').textContent=record.decisions.filter(d=>d.status==='open').map(d=>d.question||d.id).join(' ');}
function render(){ $('name').value=record.component.name;$('component-id').value=record.component.id;$('version').value=record.component.version||'';$('responsibility').value=record.responsibilities[0]?.requirement||'';$('limitation').value=record.limitations[0]?.description||'';$('questions').replaceChildren();
for(const [id,topic,,hint] of questions){const d=record.decisions.find(d=>d.id===id),section=document.createElement('section');section.className='question';const eyebrow=document.createElement('span');eyebrow.className='topic';eyebrow.textContent=topic;const h=document.createElement('h3');h.textContent=d.question||d.id;const p=document.createElement('p');p.className='hint';p.textContent=hint;const label=document.createElement('label');label.textContent='Decision status';const select=document.createElement('select');for(const [value,text] of [['open','Open question'],['decided','Decided'],['not-applicable','Not applicable']])select.add(new Option(text,value));select.value=d.status;label.append(select);const answerLabel=document.createElement('label'),area=document.createElement('textarea');area.value=d.status==='not-applicable'?d.reason||'':d.answer||'';function sync(){const s=select.value;answerLabel.firstChild.textContent=s==='not-applicable'?'Why does this not apply?':'Your decision';area.required=s!=='open';}answerLabel.append(document.createTextNode('Your decision'),area);sync();select.onchange=()=>{const s=select.value;if(s==='decided'&&!area.value.trim()||s==='not-applicable'&&!area.value.trim()){select.value='open';announce('Write a decision or reason before resolving this question.');return;}d.status=s;if(s==='not-applicable'){d.reason=area.value;delete d.answer;}else if(area.value.trim()){d.answer=area.value;delete d.reason;}sync();save();};area.oninput=()=>{if(d.status==='not-applicable')d.reason=area.value;else d.answer=area.value;if(!area.value.trim()){d.status='open';select.value='open';sync();delete d.answer;delete d.reason;}save();};section.append(eyebrow,h,p,label,answerLabel);$('questions').append(section);}update();}
for(const [id,field] of [['name','name'],['component-id','id'],['version','version']])$(id).oninput=()=>{record.component[field]=$(id).value;save();};
$('responsibility').oninput=()=>{record.responsibilities=$('responsibility').value.trim()?[{id:'consumer-input',owner:'consumer',requirement:$('responsibility').value}]:[];save();};$('limitation').oninput=()=>{record.limitations=$('limitation').value.trim()?[{id:'known-limitation',description:$('limitation').value}]:[];save();};
function download(ext,content,type){if(!record.component.name.trim()||!/^[a-z][a-z0-9-]*$/.test(record.component.id)){announce('Give the component a name and an ID using lowercase letters, digits, and hyphens.');return;}const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=`${record.component.id}.fieldnote.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Exported. Open questions remain visible.');}
$('yaml').onclick=()=>download('yaml',yaml(record)+'\n','application/yaml');$('json').onclick=()=>download('json',JSON.stringify(record,null,2)+'\n','application/json');$('markdown').onclick=()=>download('md',markdown(record),'text/markdown');
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('Choose a JSON file smaller than 1 MB.');const r=JSON.parse(await file.text());if(!compatible(r))throw Error('This worksheet imports its own modal-dialog JSON exports. Use the CLI for other fieldnotes.');record=upgrade(r);render();save();announce('Record imported.');}catch(err){announce(err.message);}e.target.value='';};
$('reset').onclick=()=>{if(confirm('Replace the current browser draft with a new record? Export first to keep it.')){record=fresh();render();save();announce('New record started.');}};render();if(!storage)announce('Browser storage is unavailable. Export your record to keep it.');
