export const schemaURL='https://raw.githubusercontent.com/marktoadvine/accessibility-fieldnote-schema/main/schema/0.1.0/fieldnote.schema.json';
export const questions=[
 ['name','semantics','What names the dialog?','Identify the visible title and how it provides the accessible name.'],
 ['initial-focus','focus','Where does focus go when it opens?','Choose an initial focus target appropriate to the content and task.'],
 ['keyboard-boundary','keyboard','How does keyboard navigation behave?','Describe Tab and Shift+Tab behavior, and how background content becomes unavailable while modal.'],
 ['dismiss','keyboard','How can someone dismiss it?','Describe Escape, the close or cancel control, and any context-dependent behavior.'],
 ['return-focus','focus','Where does focus return?','Consider the trigger and what should happen if it no longer exists.'],
 ['long-content','visual','What happens with long content or zoom?','Consider scrolling, small viewports, readable text, and keeping focused controls visible.'],
 ['reduced-motion','motion','What changes with reduced motion?','Describe which transitions are removed or reduced while keeping the interaction understandable.']
];
export function fresh(){return {$schema:schemaURL,schemaVersion:'0.1.0',component:{id:'dialogue',name:'Confirmation dialogue',platform:'web',version:'0.1.0'},guidance:{profile:'dialog-modal',version:'0.1.0'},decisions:questions.map(([id,topic,question])=>({id,topic,question,status:'open'})),responsibilities:[],limitations:[],checks:[]};}
export function compatible(r){return r&&r.schemaVersion==='0.1.0'&&r.component?.platform==='web'&&typeof r.component.name==='string'&&/^[a-z][a-z0-9-]*$/.test(r.component.id)&&Array.isArray(r.decisions)&&r.decisions.length===questions.length&&questions.every(([id])=>r.decisions.filter(d=>d.id===id).length===1)&&r.decisions.every(d=>typeof d.question==='string'&&['semantics','keyboard','focus','content','visual','motion','state','other'].includes(d.topic)&&['open','decided','not-applicable'].includes(d.status)&&(!d.answer||typeof d.answer==='string')&&(!d.reason||typeof d.reason==='string')&&(d.status!=='decided'||d.answer?.trim())&&(d.status!=='not-applicable'||d.reason?.trim()))&&['responsibilities','limitations','checks'].every(k=>Array.isArray(r[k]))&&r.responsibilities.length<=1&&r.responsibilities.every(x=>x.id==='consumer-input'&&x.owner==='consumer'&&typeof x.requirement==='string')&&r.limitations.length<=1&&r.limitations.every(x=>x.id==='known-limitation'&&typeof x.description==='string');}
export function yaml(value,indent=0){const pad=' '.repeat(indent);if(Array.isArray(value)){if(!value.length)return pad+'[]';return value.map(v=>pad+'-\n'+yaml(v,indent+2)).join('\n');}if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>typeof v==='object'&&v!==null?(Array.isArray(v)&&!v.length?pad+k+': []':pad+k+':\n'+yaml(v,indent+2)):pad+k+': '+JSON.stringify(v)).join('\n');return pad+JSON.stringify(value);}
export function markdown(r){return `# ${r.component.name} — accessibility\n\nComponent version: ${r.component.version||'unspecified'}.\n\nIntended behavior; verification is recorded separately.\n\n`+r.decisions.map(d=>`## ${d.question}\n\nStatus: **${d.status}**\n\n${d.answer||d.reason||'Unresolved.'}\n${d.answer&&d.reason?'\nReason: '+d.reason+'\n':''}`).join('\n')+'\n## Consumer responsibilities\n\n'+(r.responsibilities.map(x=>x.requirement).join('\n')||'None recorded.')+'\n\n## Known limitations\n\n'+(r.limitations.map(x=>x.description).join('\n')||'None recorded; this is not an assertion that none exist.')+'\n';}
