import pack from './dialog-modal.js';
export const schemaURL='https://raw.githubusercontent.com/marktoadvine/accessibility-fieldnote-schema/0.1.1/schema/0.1.1/fieldnote.schema.json';
export const questions=pack.questions.map(q=>[q.id,q.topic,q.question,q.hint]);
export function fresh(){return {$schema:schemaURL,schemaVersion:'0.1.1',component:{id:'dialogue',name:'Confirmation dialogue',platform:'web',version:'0.1.0'},guidance:{profile:pack.id,version:pack.version},decisions:questions.map(([id,topic,question])=>({id,topic,question,status:'open',references:pack.questions.find(q=>q.id===id).references})),responsibilities:[],limitations:[],checks:[]};}
export function compatible(r){return r&&['0.1.0','0.1.1'].includes(r.schemaVersion)&&r.component?.platform==='web'&&typeof r.component.name==='string'&&/^[a-z][a-z0-9-]*$/.test(r.component.id)&&Array.isArray(r.decisions)&&r.decisions.length===questions.length&&questions.every(([id])=>r.decisions.filter(d=>d.id===id).length===1)&&r.decisions.every(d=>(d.question===undefined||typeof d.question==='string')&&['semantics','keyboard','focus','content','visual','motion','state','other'].includes(d.topic)&&['open','decided','not-applicable'].includes(d.status)&&(!d.answer||typeof d.answer==='string')&&(!d.reason||typeof d.reason==='string')&&(d.status!=='decided'||d.answer?.trim())&&(d.status!=='not-applicable'||d.reason?.trim()))&&['responsibilities','limitations','checks'].every(k=>Array.isArray(r[k]))&&r.responsibilities.length<=1&&r.responsibilities.every(x=>x.id==='consumer-input'&&x.owner==='consumer'&&typeof x.requirement==='string')&&r.limitations.length<=1&&r.limitations.every(x=>x.id==='known-limitation'&&typeof x.description==='string');}
export function yaml(value,indent=0){const pad=' '.repeat(indent);if(Array.isArray(value)){if(!value.length)return pad+'[]';return value.map(v=>pad+'-\n'+yaml(v,indent+2)).join('\n');}if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>typeof v==='object'&&v!==null?(Array.isArray(v)&&!v.length?pad+k+': []':pad+k+':\n'+yaml(v,indent+2)):pad+k+': '+JSON.stringify(v)).join('\n');return pad+JSON.stringify(value);}
export function markdown(r){return `# ${r.component.name} — accessibility\n\nComponent version: ${r.component.version||'unspecified'}.\n\nIntended behavior; verification is recorded separately.\n\n`+r.decisions.map(d=>`## ${d.question||d.id}\n\nStatus: **${d.status}**\n\n${d.answer||d.reason||'Unresolved.'}\n${d.answer&&d.reason?'\nReason: '+d.reason+'\n':''}${(d.references||[]).map(r=>'\nSource: ['+r.standard+' '+r.version+']('+r.url+')\n').join('')}`).join('\n')+'\n## Consumer responsibilities\n\n'+(r.responsibilities.map(x=>x.requirement).join('\n')||'None recorded.')+'\n\n## Known limitations\n\n'+(r.limitations.map(x=>x.description).join('\n')||'None recorded; this is not an assertion that none exist.')+'\n';}

export function upgrade(record){return {...record,$schema:schemaURL,schemaVersion:"0.1.1"};}
